services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - cloud1-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - cloud1-network

  nginx:
    build: nginx/
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - cloud1-network
    depends_on:
      - wordpress

  wordpress:
    build: wordpress/
    container_name: wordpress
    restart: always
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - "wordpress:/var/www/html"
    depends_on:
      - mysql
    networks:
      - cloud1-network

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/data/wordpress
      o: bind

networks:
  cloud1-network:
    driver: bridge