services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - cloud1-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - cloud1-network
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - "wordpress:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/"
      - "./nginx/tools/nginx-init.sh:/tmp/nginx-init.sh"
    networks:
      - cloud1-network
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - "wordpress:/var/www/html"
      - "./wordpress/tools/wp-init.sh:/tmp/wp-init.sh"
    depends_on:
      - mysql
    networks:
      - cloud1-network

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/wordpress
      o: bind

networks:
  cloud1-network:
    driver: bridge
