services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - cloud1-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - cloud1-network
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - "wordpress:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl/certs/certificate.crt:/etc/nginx/ssl/certificate.crt"
      - "./ssl/private/private.key:/etc/nginx/ssl/private.key"
    networks:
      - cloud1-network
  # php-fpm:
  #   image: php:8.2-fpm
  #   container_name: php-fpm
  #   restart: always
  #   volumes:
  #   - "wordpress:/var/www/html"
  #   networks:
  #   - cloud1-network
  # wordpress:
  #   image: wordpress
  #   container_name: wordpress
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   env_file:
  #     - .env
  #   volumes:
  #     - "wordpress:/var/www/html"
  #     - "./wordpress/tools/wp-init.sh:/tmp/wp-init.sh"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - cloud1-network
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress
    restart: always
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - "wordpress:/var/www/html"
      - "./wordpress/tools/wp-init.sh:/tmp/wp-init.sh"
    depends_on:
      - mysql
    networks:
      - cloud1-network

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ykhadiri/data/wordpress
      o: bind

networks:
  cloud1-network:
    driver: bridge
