---
- name: Update and upgrade all packages to the latest version
  apt:
    update_cache: true

- name: Install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common

- name: Download Docker's official GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install the Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Create Project directory
  file:
    path: /home/ubuntu/cloud-1
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy docker compose file to the remote host
  copy:
    src: "../../docker-compose.yml"
    dest: /home/ubuntu/cloud-1
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy environment file to the remote host
  copy:
    src: "../../.env"
    dest: /home/ubuntu/cloud-1
    owner: ubuntu
    group: ubuntu
    mode: 0755
