services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - cloud1-network
  nginx:
    build: ./resources/nginx/.
    container_name: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - "wordpress:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - cloud1-network
  wordpress:
    build: ./resources/wordpress/.
    container_name: wordpress
    restart: always
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - "wordpress:/var/www/html"
    depends_on:
      - mysql
    networks:
      - cloud1-network

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/cloud-1/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/cloud-1/data/wordpress
      o: bind

networks:
  cloud1-network:
    driver: bridge
